#!/usr/bin/env bash

read_map() {
	LINES=0
	while read -r <&6 || return 1
	do
		((LINES < 1)) && {
			LINES=${#REPLY}
		}
		echo "$REPLY"
		((--LINES < 1)) && break
	done
}

exec 6<>/dev/tcp/"${1:-localhost}"/"${2:-51175}" || exit 1

read_map && while read -n 1 -r -p 'Command (q<>^v): '
do
	echo
	case "$REPLY" in
	q)
		break
		;;
	*)
		echo -n "$REPLY" >&6
		read_map || break
		;;
	esac
done

exec 6<&-
exec 6>&-
