#!/usr/bin/env bash
. tester &&
	tester_run_server -s 32x32 -A '8,8,>' escape &&
	tester_connect && {
		tester_read_send '>' &&
			tester_read_send '^' 8 &&
			tester_read_send '<' &&
			tester_read_send '^' 8
		tester_close
	}
tester_print_result
