#!/usr/bin/env bash
cd "${0%/*}" && . tester
tester_run_server -s 16x16 -A '6,8,>:10,8,<' rumble
tester_connect
(
	tester_connect
	tester_read_send 'f'
	tester_close
) &
wait
tester_close
tester_print_result
