#!/usr/bin/env bash
cd "${0%/*}" && . tester
tester_run_server avoid
tester_connect
tester_read_send '^'
tester_read_send 'v'
tester_read_send '^'
tester_read_send 'v'
tester_read
tester_close
tester_print_result
