#!/usr/bin/env bash
cd "${0%/*}" && . tester
tester_run_server -A '0,0,^' -R 'test' word
tester_connect
tester_read_send 't'
tester_read_send 'e'
tester_read_send 's'
tester_read_send 't'
tester_close
tester_print_result
